# Generated by Django 4.2.1 on 2023-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_separate'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='userdetailyuridik',
            name='account',
            field=models.CharField(default='1', max_length=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailyuridik',
            name='bank',
            field=models.CharField(default='1', max_length=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailyuridik',
            name='mfo',
            field=models.CharField(default='1', max_length=333),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailyuridik',
            name='name',
            field=models.CharField(default='1', max_length=123),
            preserve_default=False,
        ),
    ]
