# Generated by Django 4.2.1 on 2023-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=123)),
                ('time', models.CharField(max_length=123)),
                ('time_uz', models.CharField(max_length=123, null=True)),
                ('time_en', models.CharField(max_length=123, null=True)),
                ('time_ru', models.CharField(max_length=123, null=True)),
                ('address', models.CharField(max_length=123)),
                ('address_uz', models.CharField(max_length=123, null=True)),
                ('address_en', models.CharField(max_length=123, null=True)),
                ('address_ru', models.CharField(max_length=123, null=True)),
                ('email', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='files/')),
                ('title', models.CharField(max_length=223)),
                ('title_uz', models.CharField(max_length=223, null=True)),
                ('title_en', models.CharField(max_length=223, null=True)),
                ('title_ru', models.CharField(max_length=223, null=True)),
                ('views', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
