# Generated by Django 3.2.5 on 2023-06-23 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_property_current_price_property_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0002_message_remove_bid_bidder_remove_bid_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('cap_time', models.DateTimeField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='main.property')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='auction.auction'),
        ),
    ]
