# Generated by Django 4.2.1 on 2023-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catalogvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='text',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='text_uz',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='key',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='key_en',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='key_ru',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='key_uz',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='value',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='value_en',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='value_ru',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='value_uz',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
    ]
