# Generated by Django 4.2.1 on 2023-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='current_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
